### ISSUE TITLE
Warme herstart

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/geomagine#2]
(snapshots, bijv. ook verlopen tijd onthouden)

**Comment by RubioV** [comment]
Bij herstarten browser moet de gebruiker de optie krijgen om opnieuw te beginnen of om verder te gaan bij een eerdere snapshot.

**Comment by tomvantilburg** [comment]
Dit hangt samen met andere issues (zoals het gebruik van cow #9 ).
In ieder geval een serieuze ingreep, zowel in UI als achtergrond.
Tussen 3 en 5 dagen.

**Comment by edfennema** [comment]
Lijkt me sterk!

**Comment by tomvantilburg** [comment]
Risico van crashes is dramatisch afgenomen met het verwijderen van het 3D gedeelte. Daarom niet meer van belang.
